/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerReservasRouteImport } from './routes/owner.reservas'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerClientesRouteImport } from './routes/owner.clientes'
import { Route as OwnerChatRouteImport } from './routes/owner.chat'
import { Route as OnboardingCourtDetailsRouteImport } from './routes/onboarding.court-details'
import { Route as OnboardingCourtRouteImport } from './routes/onboarding.court'
import { Route as CourtsIdRouteImport } from './routes/courts.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReservasRoute = OwnerReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerClientesRoute = OwnerClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerChatRoute = OwnerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => OwnerRoute,
} as any)
const OnboardingCourtDetailsRoute = OnboardingCourtDetailsRouteImport.update({
  id: '/onboarding/court-details',
  path: '/onboarding/court-details',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCourtRoute = OnboardingCourtRouteImport.update({
  id: '/onboarding/court',
  path: '/onboarding/court',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIdRoute = CourtsIdRouteImport.update({
  id: '/courts/$id',
  path: '/courts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/courts/$id': typeof CourtsIdRoute
  '/onboarding/court': typeof OnboardingCourtRoute
  '/onboarding/court-details': typeof OnboardingCourtDetailsRoute
  '/owner/chat': typeof OwnerChatRoute
  '/owner/clientes': typeof OwnerClientesRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/reservas': typeof OwnerReservasRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/courts/$id': typeof CourtsIdRoute
  '/onboarding/court': typeof OnboardingCourtRoute
  '/onboarding/court-details': typeof OnboardingCourtDetailsRoute
  '/owner/chat': typeof OwnerChatRoute
  '/owner/clientes': typeof OwnerClientesRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/reservas': typeof OwnerReservasRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/courts/$id': typeof CourtsIdRoute
  '/onboarding/court': typeof OnboardingCourtRoute
  '/onboarding/court-details': typeof OnboardingCourtDetailsRoute
  '/owner/chat': typeof OwnerChatRoute
  '/owner/clientes': typeof OwnerClientesRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/reservas': typeof OwnerReservasRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/owner'
    | '/profile'
    | '/register'
    | '/search'
    | '/courts/$id'
    | '/onboarding/court'
    | '/onboarding/court-details'
    | '/owner/chat'
    | '/owner/clientes'
    | '/owner/dashboard'
    | '/owner/reservas'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/courts/$id'
    | '/onboarding/court'
    | '/onboarding/court-details'
    | '/owner/chat'
    | '/owner/clientes'
    | '/owner/dashboard'
    | '/owner/reservas'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/owner'
    | '/profile'
    | '/register'
    | '/search'
    | '/courts/$id'
    | '/onboarding/court'
    | '/onboarding/court-details'
    | '/owner/chat'
    | '/owner/clientes'
    | '/owner/dashboard'
    | '/owner/reservas'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CourtsIdRoute: typeof CourtsIdRoute
  OnboardingCourtRoute: typeof OnboardingCourtRoute
  OnboardingCourtDetailsRoute: typeof OnboardingCourtDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reservas': {
      id: '/owner/reservas'
      path: '/reservas'
      fullPath: '/owner/reservas'
      preLoaderRoute: typeof OwnerReservasRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/clientes': {
      id: '/owner/clientes'
      path: '/clientes'
      fullPath: '/owner/clientes'
      preLoaderRoute: typeof OwnerClientesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/chat': {
      id: '/owner/chat'
      path: '/chat'
      fullPath: '/owner/chat'
      preLoaderRoute: typeof OwnerChatRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/onboarding/court-details': {
      id: '/onboarding/court-details'
      path: '/onboarding/court-details'
      fullPath: '/onboarding/court-details'
      preLoaderRoute: typeof OnboardingCourtDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/court': {
      id: '/onboarding/court'
      path: '/onboarding/court'
      fullPath: '/onboarding/court'
      preLoaderRoute: typeof OnboardingCourtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$id': {
      id: '/courts/$id'
      path: '/courts/$id'
      fullPath: '/courts/$id'
      preLoaderRoute: typeof CourtsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OwnerRouteChildren {
  OwnerChatRoute: typeof OwnerChatRoute
  OwnerClientesRoute: typeof OwnerClientesRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerReservasRoute: typeof OwnerReservasRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerChatRoute: OwnerChatRoute,
  OwnerClientesRoute: OwnerClientesRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerReservasRoute: OwnerReservasRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CourtsIdRoute: CourtsIdRoute,
  OnboardingCourtRoute: OnboardingCourtRoute,
  OnboardingCourtDetailsRoute: OnboardingCourtDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
