/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogadorReservasRouteImport } from './routes/jogador.reservas'
import { Route as JogadorPerfilRouteImport } from './routes/jogador.perfil'
import { Route as JogadorMenuRouteImport } from './routes/jogador.menu'
import { Route as DonoPerfilRouteImport } from './routes/dono.perfil'
import { Route as DonoMenuRouteImport } from './routes/dono.menu'
import { Route as DonoHorariosRouteImport } from './routes/dono.horarios'
import { Route as DonoEditarQuadraRouteImport } from './routes/dono.editar-quadra'
import { Route as DonoDashboardRouteImport } from './routes/dono.dashboard'
import { Route as DonoCadastroQuadra2RouteImport } from './routes/dono.cadastro-quadra-2'
import { Route as DonoCadastroQuadra1RouteImport } from './routes/dono.cadastro-quadra-1'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as JogadorFinalizarQuadraIdRouteImport } from './routes/jogador.finalizar.$quadraId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorReservasRoute = JogadorReservasRouteImport.update({
  id: '/jogador/reservas',
  path: '/jogador/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorPerfilRoute = JogadorPerfilRouteImport.update({
  id: '/jogador/perfil',
  path: '/jogador/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorMenuRoute = JogadorMenuRouteImport.update({
  id: '/jogador/menu',
  path: '/jogador/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoPerfilRoute = DonoPerfilRouteImport.update({
  id: '/dono/perfil',
  path: '/dono/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoMenuRoute = DonoMenuRouteImport.update({
  id: '/dono/menu',
  path: '/dono/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoHorariosRoute = DonoHorariosRouteImport.update({
  id: '/dono/horarios',
  path: '/dono/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoEditarQuadraRoute = DonoEditarQuadraRouteImport.update({
  id: '/dono/editar-quadra',
  path: '/dono/editar-quadra',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoDashboardRoute = DonoDashboardRouteImport.update({
  id: '/dono/dashboard',
  path: '/dono/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoCadastroQuadra2Route = DonoCadastroQuadra2RouteImport.update({
  id: '/dono/cadastro-quadra-2',
  path: '/dono/cadastro-quadra-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoCadastroQuadra1Route = DonoCadastroQuadra1RouteImport.update({
  id: '/dono/cadastro-quadra-1',
  path: '/dono/cadastro-quadra-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/auth/cadastro',
  path: '/auth/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorFinalizarQuadraIdRoute =
  JogadorFinalizarQuadraIdRouteImport.update({
    id: '/jogador/finalizar/$quadraId',
    path: '/jogador/finalizar/$quadraId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/dono/cadastro-quadra-1': typeof DonoCadastroQuadra1Route
  '/dono/cadastro-quadra-2': typeof DonoCadastroQuadra2Route
  '/dono/dashboard': typeof DonoDashboardRoute
  '/dono/editar-quadra': typeof DonoEditarQuadraRoute
  '/dono/horarios': typeof DonoHorariosRoute
  '/dono/menu': typeof DonoMenuRoute
  '/dono/perfil': typeof DonoPerfilRoute
  '/jogador/menu': typeof JogadorMenuRoute
  '/jogador/perfil': typeof JogadorPerfilRoute
  '/jogador/reservas': typeof JogadorReservasRoute
  '/jogador/finalizar/$quadraId': typeof JogadorFinalizarQuadraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/dono/cadastro-quadra-1': typeof DonoCadastroQuadra1Route
  '/dono/cadastro-quadra-2': typeof DonoCadastroQuadra2Route
  '/dono/dashboard': typeof DonoDashboardRoute
  '/dono/editar-quadra': typeof DonoEditarQuadraRoute
  '/dono/horarios': typeof DonoHorariosRoute
  '/dono/menu': typeof DonoMenuRoute
  '/dono/perfil': typeof DonoPerfilRoute
  '/jogador/menu': typeof JogadorMenuRoute
  '/jogador/perfil': typeof JogadorPerfilRoute
  '/jogador/reservas': typeof JogadorReservasRoute
  '/jogador/finalizar/$quadraId': typeof JogadorFinalizarQuadraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/dono/cadastro-quadra-1': typeof DonoCadastroQuadra1Route
  '/dono/cadastro-quadra-2': typeof DonoCadastroQuadra2Route
  '/dono/dashboard': typeof DonoDashboardRoute
  '/dono/editar-quadra': typeof DonoEditarQuadraRoute
  '/dono/horarios': typeof DonoHorariosRoute
  '/dono/menu': typeof DonoMenuRoute
  '/dono/perfil': typeof DonoPerfilRoute
  '/jogador/menu': typeof JogadorMenuRoute
  '/jogador/perfil': typeof JogadorPerfilRoute
  '/jogador/reservas': typeof JogadorReservasRoute
  '/jogador/finalizar/$quadraId': typeof JogadorFinalizarQuadraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/cadastro'
    | '/auth/login'
    | '/dono/cadastro-quadra-1'
    | '/dono/cadastro-quadra-2'
    | '/dono/dashboard'
    | '/dono/editar-quadra'
    | '/dono/horarios'
    | '/dono/menu'
    | '/dono/perfil'
    | '/jogador/menu'
    | '/jogador/perfil'
    | '/jogador/reservas'
    | '/jogador/finalizar/$quadraId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/cadastro'
    | '/auth/login'
    | '/dono/cadastro-quadra-1'
    | '/dono/cadastro-quadra-2'
    | '/dono/dashboard'
    | '/dono/editar-quadra'
    | '/dono/horarios'
    | '/dono/menu'
    | '/dono/perfil'
    | '/jogador/menu'
    | '/jogador/perfil'
    | '/jogador/reservas'
    | '/jogador/finalizar/$quadraId'
  id:
    | '__root__'
    | '/'
    | '/auth/cadastro'
    | '/auth/login'
    | '/dono/cadastro-quadra-1'
    | '/dono/cadastro-quadra-2'
    | '/dono/dashboard'
    | '/dono/editar-quadra'
    | '/dono/horarios'
    | '/dono/menu'
    | '/dono/perfil'
    | '/jogador/menu'
    | '/jogador/perfil'
    | '/jogador/reservas'
    | '/jogador/finalizar/$quadraId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DonoCadastroQuadra1Route: typeof DonoCadastroQuadra1Route
  DonoCadastroQuadra2Route: typeof DonoCadastroQuadra2Route
  DonoDashboardRoute: typeof DonoDashboardRoute
  DonoEditarQuadraRoute: typeof DonoEditarQuadraRoute
  DonoHorariosRoute: typeof DonoHorariosRoute
  DonoMenuRoute: typeof DonoMenuRoute
  DonoPerfilRoute: typeof DonoPerfilRoute
  JogadorMenuRoute: typeof JogadorMenuRoute
  JogadorPerfilRoute: typeof JogadorPerfilRoute
  JogadorReservasRoute: typeof JogadorReservasRoute
  JogadorFinalizarQuadraIdRoute: typeof JogadorFinalizarQuadraIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/reservas': {
      id: '/jogador/reservas'
      path: '/jogador/reservas'
      fullPath: '/jogador/reservas'
      preLoaderRoute: typeof JogadorReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/perfil': {
      id: '/jogador/perfil'
      path: '/jogador/perfil'
      fullPath: '/jogador/perfil'
      preLoaderRoute: typeof JogadorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/menu': {
      id: '/jogador/menu'
      path: '/jogador/menu'
      fullPath: '/jogador/menu'
      preLoaderRoute: typeof JogadorMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/perfil': {
      id: '/dono/perfil'
      path: '/dono/perfil'
      fullPath: '/dono/perfil'
      preLoaderRoute: typeof DonoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/menu': {
      id: '/dono/menu'
      path: '/dono/menu'
      fullPath: '/dono/menu'
      preLoaderRoute: typeof DonoMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/horarios': {
      id: '/dono/horarios'
      path: '/dono/horarios'
      fullPath: '/dono/horarios'
      preLoaderRoute: typeof DonoHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/editar-quadra': {
      id: '/dono/editar-quadra'
      path: '/dono/editar-quadra'
      fullPath: '/dono/editar-quadra'
      preLoaderRoute: typeof DonoEditarQuadraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/dashboard': {
      id: '/dono/dashboard'
      path: '/dono/dashboard'
      fullPath: '/dono/dashboard'
      preLoaderRoute: typeof DonoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/cadastro-quadra-2': {
      id: '/dono/cadastro-quadra-2'
      path: '/dono/cadastro-quadra-2'
      fullPath: '/dono/cadastro-quadra-2'
      preLoaderRoute: typeof DonoCadastroQuadra2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono/cadastro-quadra-1': {
      id: '/dono/cadastro-quadra-1'
      path: '/dono/cadastro-quadra-1'
      fullPath: '/dono/cadastro-quadra-1'
      preLoaderRoute: typeof DonoCadastroQuadra1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/finalizar/$quadraId': {
      id: '/jogador/finalizar/$quadraId'
      path: '/jogador/finalizar/$quadraId'
      fullPath: '/jogador/finalizar/$quadraId'
      preLoaderRoute: typeof JogadorFinalizarQuadraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
  DonoCadastroQuadra1Route: DonoCadastroQuadra1Route,
  DonoCadastroQuadra2Route: DonoCadastroQuadra2Route,
  DonoDashboardRoute: DonoDashboardRoute,
  DonoEditarQuadraRoute: DonoEditarQuadraRoute,
  DonoHorariosRoute: DonoHorariosRoute,
  DonoMenuRoute: DonoMenuRoute,
  DonoPerfilRoute: DonoPerfilRoute,
  JogadorMenuRoute: JogadorMenuRoute,
  JogadorPerfilRoute: JogadorPerfilRoute,
  JogadorReservasRoute: JogadorReservasRoute,
  JogadorFinalizarQuadraIdRoute: JogadorFinalizarQuadraIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
